### ISSUE TITLE
Introduce serial and parallel version of PW can be compiled in documents

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#1677]
### Describe Current Status and Possible Solution

Documents should introduce the following:
Serial and parallel version of PW can be compiled.
Some libraries like Elpa and libRI are optional.

They should be introduced both in [https://github.com/deepmodeling/abacus-develop/wiki/Building-and-Running-ABACUS](url) and [https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#install-requirements](url)

**Comment by caic99** [comment]
@Qianruipku The wiki page is deprecated, and only for the installation of dependencies. Our document page has contained such info at https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#prerequisites .

**Comment by Liu-RX** [comment]
The compilation of parallel version of PW has been introduced through `ENABLE_LCAO` option in the CMake and corresponding CI is added already. For the serial version, I was able to successfully compile it with CMake, but serial PW fails on SCF calculation due to the following segmentation error.
```
DONE(1.62126    SEC) : INIT BASIS
 -------------------------------------------
 SELF-CONSISTENT :
 -------------------------------------------
 START CHARGE      : atomic
 DONE(1.64799    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2159==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x56140557d178 bp 0x7ffe0cbaf100 sp 0x7ffe0cbaef80 T0)
==2159==The signal is caused by a READ memory access.
==2159==Hint: address points to the zero page.
    #0 0x56140557d178 in void WF_atomic::random_t<double>(std::complex<double>*, int, int, int, ModulePW::PW_Basis_K*) /abacus-develop/source/module_hamilt_pw/hamilt_pwdft/wf_atomic.cpp:625
    #1 0x56140557d178 in WF_atomic::random(std::complex<double>*, int, int, int, ModulePW::PW_Basis_K*) /abacus-develop/source/module_hamilt_pw/hamilt_pwdft/wf_atomic.cpp:551
    #2 0x561405578754 in hamilt::diago_PAO_in_pw_k2(int const&, psi::Psi<std::complex<double>, psi::DEVICE_CPU>&, hamilt::Hamilt<double, psi::DEVICE_CPU>*) /abacus-develop/source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp:322
    #3 0x5614054586cf in hsolver::HSolverPW<double, psi::DEVICE_CPU>::updatePsiK(hamilt::Hamilt<double, psi::DEVICE_CPU>*, psi::Psi<std::complex<double>, psi::DEVICE_CPU>&, int) /abacus-develop/source/module_hsolver/hsolver_pw.cpp:166
    #4 0x56140545b940 in hsolver::HSolverPW<double, psi::DEVICE_CPU>::solve(hamilt::Hamilt<double, psi::DEVICE_CPU>*, psi::Psi<std::complex<double>, psi::DEVICE_CPU>&, elecstate::ElecState*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) /abacus-develop/source/module_hsolver/hsolver_pw.cpp:95
    #5 0x5614056021ba in ModuleESolver::ESolver_KS_PW<double, psi::DEVICE_CPU>::hamilt2density(int, int, double) /abacus-develop/source/module_esolver/esolver_ks_pw.cpp:391
    #6 0x5614055ea2bc in ModuleESolver::ESolver_KS<double, psi::DEVICE_CPU>::Run(int, UnitCell&) /abacus-develop/source/module_esolver/esolver_ks.cpp:204
    #7 0x5614053cdf44 in Relax_Driver::relax_driver(ModuleESolver::ESolver*) /abacus-develop/source/module_relax/relax_driver.cpp:40
    #8 0x5614053fca29 in Driver::driver_run() /abacus-develop/source/driver_run.cpp:57
    #9 0x5614053f8f40 in Driver::atomic_world() /abacus-develop/source/driver.cpp:95
    #10 0x5614053fb568 in Driver::init() /abacus-develop/source/driver.cpp:35
    #11 0x56140509cc44 in main /abacus-develop/source/main.cpp:15
    #12 0x7f45d7cc2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #13 0x7f45d7cc2e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #14 0x5614050c4f04 in _start (/abacus-develop/build/abacus_pw+0x10bf04)
```
The bug has to be solved so that serial version could be used without bug.
@Qianruipku
