### ISSUE TITLE
Memory leak in ORB_table_alpha.cpp

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#2100]
### Describe the bug

The following memory leaks are detected 
```
3: Direct leak of 32 byte(s) in 2 object(s) allocated from:
[7086](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7087)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7087](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7088)
3:     #1 0x55ad635cee3b in ORB_table_alpha::init_Table_Alpha(ModuleBase::Sph_Bessel_Recursive::D2*, LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_alpha.cpp:251
[7088](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7089)
3:     #2 0x55ad635a7650 in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:116
[7089](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7090)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7090](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7091)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7091](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7092)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7092](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7093)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7093](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7094)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7094](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7095)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 30176640 byte(s) in 3120 object(s) allocated from:
[7179](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7180)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7180](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7181)
3:     #1 0x55ad635cf921 in ORB_table_alpha::init_Table_Alpha(ModuleBase::Sph_Bessel_Recursive::D2*, LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_alpha.cpp:314
[7181](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7182)
3:     #2 0x55ad635a7650 in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:116
[7182](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7183)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7183](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7184)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7184](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7185)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7185](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7186)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7186](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7187)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7187](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7188)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 30176640 byte(s) in 3120 object(s) allocated from:
[7190](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7191)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7191](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7192)
3:     #1 0x55ad635cfa11 in ORB_table_alpha::init_Table_Alpha(ModuleBase::Sph_Bessel_Recursive::D2*, LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_alpha.cpp:315
[7192](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7193)
3:     #2 0x55ad635a7650 in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:116
[7193](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7194)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7194](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7195)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7195](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7196)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7196](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7197)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7197](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7198)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7198](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7199)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 24960 byte(s) in 624 object(s) allocated from:
[7299](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7300)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7300](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7301)
3:     #1 0x55ad635cf449 in ORB_table_alpha::init_Table_Alpha(ModuleBase::Sph_Bessel_Recursive::D2*, LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_alpha.cpp:292
[7301](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7302)
3:     #2 0x55ad635a7650 in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:116
[7302](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7303)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7303](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7304)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7304](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7305)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7305](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7306)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7306](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7307)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7307](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7308)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 4992 byte(s) in 4 object(s) allocated from:
[7362](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7363)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7363](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7364)
3:     #1 0x55ad635cf148 in ORB_table_alpha::init_Table_Alpha(ModuleBase::Sph_Bessel_Recursive::D2*, LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_alpha.cpp:276
[7364](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7365)
3:     #2 0x55ad635a7650 in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:116
[7365](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7366)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7366](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7367)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7367](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7368)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7368](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7369)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7369](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7370)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7370](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7371)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 4992 byte(s) in 4 object(s) allocated from:
[7351](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7352)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7352](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7353)
3:     #1 0x55ad635cf19e in ORB_table_alpha::init_Table_Alpha(ModuleBase::Sph_Bessel_Recursive::D2*, LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_alpha.cpp:277
[7353](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7354)
3:     #2 0x55ad635a7650 in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:116
[7354](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7355)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7355](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7356)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7356](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7357)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7357](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7358)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7358](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7359)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7359](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7360)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 24960 byte(s) in 624 object(s) allocated from:
[7310](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7311)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7311](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7312)
3:     #1 0x55ad635cf4bd in ORB_table_alpha::init_Table_Alpha(ModuleBase::Sph_Bessel_Recursive::D2*, LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_alpha.cpp:293
[7312](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7313)
3:     #2 0x55ad635a7650 in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:116
[7313](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7314)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7314](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7315)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7315](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7316)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7316](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7317)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7317](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7318)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7318](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7319)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
```

in test case `604_NO_deepks_ut_H2O_multik `.

**Comment by hongriTianqi** [comment]
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).
