### ISSUE TITLE
Memory leak in ORB_table_beta.cpp

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#2101]
### Describe the bug

The follow memory leaks are detected 
```
3: Direct leak of 32 byte(s) in 2 object(s) allocated from:
[7108](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7109)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7109](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7110)
3:     #1 0x55ad635d7839 in ORB_table_beta::init_Table_Beta(ModuleBase::Sph_Bessel_Recursive::D2*, Numerical_Orbital const*, Numerical_Nonlocal const*, int const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_beta.cpp:234
[7110](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7111)
3:     #2 0x55ad635a71cb in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:111
[7111](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7112)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7112](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7113)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7113](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7114)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7114](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7115)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7115](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7116)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7116](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7117)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)



3: Indirect leak of 3264 byte(s) in 96 object(s) allocated from:
[7373](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7374)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7374](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7375)
3:     #1 0x55ad635d7f11 in ORB_table_beta::init_Table_Beta(ModuleBase::Sph_Bessel_Recursive::D2*, Numerical_Orbital const*, Numerical_Nonlocal const*, int const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_beta.cpp:284
[7375](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7376)
3:     #2 0x55ad635a71cb in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:111
[7376](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7377)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7377](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7378)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7378](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7379)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7379](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7380)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7380](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7381)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7381](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7382)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 3264 byte(s) in 96 object(s) allocated from:
[7384](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7385)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7385](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7386)
3:     #1 0x55ad635d7f8a in ORB_table_beta::init_Table_Beta(ModuleBase::Sph_Bessel_Recursive::D2*, Numerical_Orbital const*, Numerical_Nonlocal const*, int const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_beta.cpp:285
[7386](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7387)
3:     #2 0x55ad635a71cb in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:111
[7387](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7388)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7388](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7389)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7389](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7390)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7390](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7391)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7391](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7392)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7392](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7393)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 2407744 byte(s) in 408 object(s) allocated from:
[7256](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7257)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7257](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7258)
3:     #1 0x55ad635d82a7 in ORB_table_beta::init_Table_Beta(ModuleBase::Sph_Bessel_Recursive::D2*, Numerical_Orbital const*, Numerical_Nonlocal const*, int const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_beta.cpp:297
[7258](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7259)
3:     #2 0x55ad635a71cb in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:111
[7259](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7260)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7260](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7261)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7261](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7262)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7262](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7263)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7263](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7264)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7264](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7265)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)



3: Indirect leak of 2407744 byte(s) in 408 object(s) allocated from:
[7245](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7246)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7246](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7247)
3:     #1 0x55ad635d8397 in ORB_table_beta::init_Table_Beta(ModuleBase::Sph_Bessel_Recursive::D2*, Numerical_Orbital const*, Numerical_Nonlocal const*, int const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_beta.cpp:298
[7247](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7248)
3:     #2 0x55ad635a71cb in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:111
[7248](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7249)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7249](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7250)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7250](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7251)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7251](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7252)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7252](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7253)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7253](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7254)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
```

in test case of `604_NO_deepks_ut_H2O_multik `.

**Comment by hongriTianqi** [comment]
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).
