### ISSUE TITLE
Memory leak in ORB_table_phi.cpp

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#2102]
### Describe the bug

The following memory leaks are detected
```
3: Direct leak of 32 byte(s) in 2 object(s) allocated from:
[7097](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7098)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7098](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7099)
3:     #1 0x55ad635e1054 in ORB_table_phi::init_Table(LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_phi.cpp:392
[7099](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7100)
3:     #2 0x55ad635a715d in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:107
[7100](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7101)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7101](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7102)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7102](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7103)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7103](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7104)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7104](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7105)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7105](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7106)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Direct leak of 32 byte(s) in 2 object(s) allocated from:
[7119](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7120)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7120](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7121)
3:     #1 0x55ad635e102f in ORB_table_phi::init_Table(LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_phi.cpp:391
[7121](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7122)
3:     #2 0x55ad635a715d in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:107
[7122](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7123)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7123](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7124)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7124](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7125)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7125](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7126)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7126](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7127)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7127](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7128)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)



3: Indirect leak of 1568 byte(s) in 12 object(s) allocated from:
[7419](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7420)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7420](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7421)
3:     #1 0x55ad635e13ad in ORB_table_phi::init_Table(LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_phi.cpp:433
[7421](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7422)
3:     #2 0x55ad635a715d in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:107
[7422](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7423)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7423](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7424)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7424](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7425)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7425](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7426)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7426](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7427)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7427](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7428)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 1568 byte(s) in 12 object(s) allocated from:
[7430](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7431)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7431](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7432)
3:     #1 0x55ad635e1406 in ORB_table_phi::init_Table(LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_phi.cpp:434
[7432](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7433)
3:     #2 0x55ad635a715d in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:107
[7433](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7434)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7434](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7435)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7435](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7436)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7436](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7437)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7437](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7438)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7438](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7439)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)



3: Indirect leak of 7264 byte(s) in 196 object(s) allocated from:
[7340](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7341)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7341](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7342)
3:     #1 0x55ad635e17d3 in ORB_table_phi::init_Table(LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_phi.cpp:469
[7342](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7343)
3:     #2 0x55ad635a715d in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:107
[7343](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7344)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7344](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7345)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7345](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7346)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7346](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7347)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7347](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7348)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7348](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7349)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 7264 byte(s) in 196 object(s) allocated from:
[7329](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7330)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7330](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7331)
3:     #1 0x55ad635e184a in ORB_table_phi::init_Table(LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_phi.cpp:470
[7331](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7332)
3:     #2 0x55ad635a715d in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:107
[7332](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7333)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7333](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7334)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7334](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7335)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7335](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7336)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7336](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7337)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7337](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7338)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)



3: Indirect leak of 4376560 byte(s) in 454 object(s) allocated from:
[7201](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7202)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7202](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7203)
3:     #1 0x55ad635e1ec9 in ORB_table_phi::init_Table(LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_phi.cpp:480
[7203](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7204)
3:     #2 0x55ad635a715d in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:107
[7204](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7205)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7205](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7206)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7206](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7207)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7207](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7208)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7208](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7209)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7209](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7210)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 4376560 byte(s) in 454 object(s) allocated from:
[7223](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7224)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7224](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7225)
3:     #1 0x55ad635e20a1 in ORB_table_phi::init_Table(LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_phi.cpp:482
[7225](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7226)
3:     #2 0x55ad635a715d in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:107
[7226](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7227)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7227](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7228)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7228](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7229)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7229](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7230)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7230](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7231)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7231](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7232)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 4366920 byte(s) in 453 object(s) allocated from:
[7234](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7235)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7235](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7236)
3:     #1 0x55ad635e1fb5 in ORB_table_phi::init_Table(LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_phi.cpp:481
[7236](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7237)
3:     #2 0x55ad635a715d in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:107
[7237](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7238)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7238](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7239)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7239](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7240)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7240](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7241)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7241](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7242)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7242](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7243)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)


3: Indirect leak of 4376560 byte(s) in 454 object(s) allocated from:
[7212](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7213)
3:     #0 0x7f59e6f89337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
[7213](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7214)
3:     #1 0x55ad635e2192 in ORB_table_phi::init_Table(LCAO_Orbitals&) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_table_phi.cpp:483
[7214](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7215)
3:     #2 0x55ad635a715d in ORB_gen_tables::gen_tables(std::basic_ofstream<char, std::char_traits<char> >&, LCAO_Orbitals&, int const&, bool const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_gen_tables.cpp:107
[7215](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7216)
3:     #3 0x55ad63594cb1 in ORB_control::set_orb_tables(std::basic_ofstream<char, std::char_traits<char> >&, ORB_gen_tables&, LCAO_Orbitals&, double const&, bool const&, int const&, int const&, int const*, Numerical_Nonlocal const*) /__w/abacus-develop/abacus-develop/source/module_orbital/ORB_control.cpp:132
[7216](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7217)
3:     #4 0x55ad6333774e in test_deepks::set_orbs(double const&) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:175
[7217](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7218)
3:     #5 0x55ad6333b013 in test_deepks::preparation() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp:13
[7218](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7219)
3:     #6 0x55ad6331ca18 in calculate() /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:32
[7219](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7220)
3:     #7 0x55ad632efa21 in main /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp:13
[7220](https://github.com/deepmodeling/abacus-develop/actions/runs/4443809885/jobs/7801429911#step:5:7221)
3:     #8 0x7f59d07c2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
```

in test case of `604_NO_deepks_ut_H2O_multik `.

**Comment by hongriTianqi** [comment]
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).
