### ISSUE TITLE
memory leak in Record_adj::for_2d(Parallel_Orbitals&, bool)

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#2148]
### Describe the bug

The following memory leak is detected:
```
Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f36e58fb337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
    #1 0x55f63764bfb9 in Record_adj::for_2d(Parallel_Orbitals&, bool) /__w/abacus-develop/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/record_adj.cpp:154
    #2 0x55f6374f1505 in ModuleESolver::ESolver_KS_LCAO::set_matrix_grid(Record_adj&) /__w/abacus-develop/abacus-develop/source/module_esolver/esolver_ks_lcao_elec.cpp:65
    #3 0x55f6374f5e65 in ModuleESolver::ESolver_KS_LCAO::beforesolver(int) /__w/abacus-develop/abacus-develop/source/module_esolver/esolver_ks_lcao_elec.cpp:89
    #4 0x55f6374fa797 in ModuleESolver::ESolver_KS_LCAO::othercalculation(int) /__w/abacus-develop/abacus-develop/source/module_esolver/esolver_ks_lcao_elec.cpp:397
    #5 0x55f637459b9c in ModuleESolver::ESolver_KS<double, psi::DEVICE_CPU>::Run(int, UnitCell&) /__w/abacus-develop/abacus-develop/source/module_esolver/esolver_ks.cpp:187
    #6 0x55f6371df12f in Relax_Driver::relax_driver(ModuleESolver::ESolver*) /__w/abacus-develop/abacus-develop/source/module_relax/relax_driver.cpp:40
    #7 0x55f63721404c in Driver::driver_run() /__w/abacus-develop/abacus-develop/source/driver_run.cpp:59
    #8 0x55f6372105de in Driver::atomic_world() /__w/abacus-develop/abacus-develop/source/driver.cpp:95
    #9 0x55f637212e36 in Driver::init() /__w/abacus-develop/abacus-develop/source/driver.cpp:35
    #10 0x55f636cc78b4 in main /__w/abacus-develop/abacus-develop/source/main.cpp:15
```

in test case of `207_NO_KP_OB`.

**Comment by lcclcc233** [comment]
Fixed by #2294
