### ISSUE TITLE
check if there is a new line in the STRU file

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2366]
### Describe Current Status and Possible Solution

I often use `ase-abacus` to transform `STRU` to `cif` file.
But if there is no new lines (or empty lines) at the end of `STRU` file, `ase-abacus` wouldn't work correctly. This might be common issue for coding. I suggest there should be checks if there is a new empty line at the end of all files.

the script I use is very simple
```
from ase.io import read, write
from pathlib import Path

cs_dir = './'
cs_cif = Path(cs_dir, 'STRU')#modify name
cs_atoms = read(cs_cif, format='abacus')
cs_stru = Path(cs_dir, 'STRU.cif')#modify name
write(cs_stru, cs_atoms, format='cif')
```
but it failed if the `STRU` file doesn't have a empty line, e.g. `examples/md/lcao_gammaonly_Sn64/STRU`
```
(abacus) alma@DESKTOP-8EH3B7O:~/software/abacus-develop/examples/md/lcao_gammaonly_Sn64$ python abacus2cif.py
Traceback (most recent call last):
  File "/home/alma/software/abacus-develop/examples/md/lcao_gammaonly_Sn64/abacus2cif.py", line 6, in <module>
    cs_atoms = read(cs_cif, format='abacus')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alma/miniconda3/envs/abacus/lib/python3.11/site-packages/ase-3.23.0b1-py3.11.egg/ase/io/formats.py", line 777, in read
    return next(_iread(filename, slice(index, None), format, io,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alma/miniconda3/envs/abacus/lib/python3.11/site-packages/ase-3.23.0b1-py3.11.egg/ase/parallel.py", line 285, in new_generator
    for result in generator(*args, **kwargs):
  File "/home/alma/miniconda3/envs/abacus/lib/python3.11/site-packages/ase-3.23.0b1-py3.11.egg/ase/io/formats.py", line 844, in _iread
    for dct in io.read(fd, *args, **kwargs):
  File "/home/alma/miniconda3/envs/abacus/lib/python3.11/site-packages/ase-3.23.0b1-py3.11.egg/ase/io/formats.py", line 598, in wrap_read_function
    yield read(filename, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alma/miniconda3/envs/abacus/lib/python3.11/site-packages/ase-3.23.0b1-py3.11.egg/ase/utils/__init__.py", line 487, in iofunc
    obj = func(fd, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alma/miniconda3/envs/abacus/lib/python3.11/site-packages/ase-3.23.0b1-py3.11.egg/ase/io/abacus.py", line 702, in read_abacus
    atoms = Atoms(symbols=atom_symbol,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alma/miniconda3/envs/abacus/lib/python3.11/site-packages/ase-3.23.0b1-py3.11.egg/ase/atoms.py", line 229, in __init__
    self.new_array('positions', positions, float, (3,))
  File "/home/alma/miniconda3/envs/abacus/lib/python3.11/site-packages/ase-3.23.0b1-py3.11.egg/ase/atoms.py", line 468, in new_array
    raise ValueError('Array "%s" has wrong length: %d != %d.' %
ValueError: Array "positions" has wrong length: 63 != 64.
(abacus) alma@DESKTOP-8EH3B7O:~/software/abacus-develop/examples/md/lcao_gammaonly_Sn64$
```

**Comment by hongriTianqi** [comment]
A [PR](https://gitlab.com/1041176461/ase-abacus/-/merge_requests/4/diffs) on ase-abacus has been submitted to solve this issue. @Satinelamp @baixiaokuang @1041176461

**Comment by 1041176461** [comment]
> A [PR](https://gitlab.com/1041176461/ase-abacus/-/merge_requests/4/diffs) on asa-abacus has been submitted to solve this issue. @Satinelamp @baixiaokuang @1041176461

@hongriTianqi Thanks! It have been merged.

**Comment by hongriTianqi** [comment]
I will close this issue as has been solved. @Satinelamp
