### ISSUE TITLE
Bug in lcao gamma_only calculations when using one core

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#2386]
### Describe the bug

Taking integrated tests **308_NO_GO_RE_MB** as an example, if the test is run by **one** core, the program will crash and report the error log as follows: 

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2168342==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f2792e9285a bp 0xffffffffffffffff sp 0x7ffe756c0a48 T0)
==2168342==The signal is caused by a READ memory access.
==2168342==Hint: address points to the zero page.
    #0 0x7f2792e92859 in ofi_av_get_addr (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x2e859)
    #1 0x7f2792e92878 in ofi_av_addr_context (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x2e878)
    #2 0x7f2792e729e4 in sc_get_connection (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0xe9e4)
    #3 0x7f2792e77c16 in rxm_finish_recv (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x13c16)
    #4 0x7f2792e78388 in rxm_match_rx_buf (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x14388)
    #5 0x7f2792e790af in rxm_handle_recv_comp (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x150af)
    #6 0x7f2792e79a99 in rxm_handle_comp (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x15a99)
    #7 0x7f2792e7ab22 in rxm_ep_do_progress (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x16b22)
    #8 0x7f2792e7ace8 in rxm_ep_progress (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x16ce8)
    #9 0x7f2792e95a3c in ofi_cq_progress (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x31a3c)
    #10 0x7f2792e959c6 in ofi_cq_readfrom (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x319c6)
    #11 0x7f279ff5bf3d in fi_cq_read /p/pdsd/scratch/Uploads/IMPI/other/software/libfabric/linux/v1.9.0/include/rdma/fi_eq.h:385
    #12 0x7f279ff5bf3d in MPIDI_OFI_progress ../../src/mpid/ch4/netmod/ofi/ofi_progress.c:28
    #13 0x7f279fb2f180 in MPIDI_Progress_test ../../src/mpid/ch4/src/ch4_progress.c:89
    #14 0x7f279fb2f180 in MPID_Progress_test_impl ../../src/mpid/ch4/src/ch4_progress.c:117
    #15 0x7f279fb2f180 in MPID_Progress_wait ../../src/mpid/ch4/src/ch4_progress.c:163
    #16 0x7f27a00bbec0 in MPIR_Waitall_impl ../../src/mpi/request/waitall.c:44
    #17 0x7f27a00bbec0 in MPID_Waitall ../../src/mpid/ch4/include/mpidpost.h:113
    #18 0x7f27a00bbec0 in MPIR_Waitall ../../src/mpi/request/waitall.c:179
    #19 0x7f279fcbda49 in MPIC_Waitall ../../src/mpi/coll/helper_fns.c:700
    #20 0x7f279fa6d420 in MPIR_Alltoallv_intra_scattered_impl ../../src/mpi/coll/intel/alltoallv/alltoallv_intra_scattered.c:224
    #21 0x7f279fa6d420 in MPIR_Alltoallv_intra_scattered ../../src/mpi/coll/intel/alltoallv/alltoallv_intra_scattered.c:106
    #22 0x7f279fa5c6c8 in MPIR_Alltoallv_intra_auto ../../src/mpi/coll/intel/alltoallv/alltoallv_allcomm_auto.c:43
    #23 0x7f279faba9c4 in MPIDI_NM_mpi_alltoallv ../../src/mpid/ch4/netmod/include/../ofi/intel/ofi_coll.h:684
    #24 0x7f279faba9c4 in MPIDI_Alltoallv_intra_composition_alpha ../../src/mpid/ch4/src/intel/ch4_coll_impl.h:1794
    #25 0x7f279faba9c4 in MPID_Alltoallv_invoke ../../src/mpid/ch4/src/intel/ch4_coll_select_utils.c:2276
    #26 0x7f279faba9c4 in MPIDI_coll_invoke ../../src/mpid/ch4/src/intel/ch4_coll_select_utils.c:3335
    #27 0x7f279fa99a7f in MPIDI_coll_select ../../src/mpid/ch4/src/intel/ch4_coll_globals_default.c:143
    #28 0x7f279fb9b88e in MPID_Alltoallv ../../src/mpid/ch4/src/intel/ch4_coll.h:240
    #29 0x7f279fb9b88e in MPIR_Alltoallv ../../src/mpi/coll/intel/src/coll_impl.c:309
    #30 0x7f279fa6ed83 in PMPI_Alltoallv ../../src/mpi/coll/alltoallv/alltoallv.c:369
    #31 0x5597a01a91cd in Local_Orbital_Charge::setAlltoallvParameter(int, int, int) /home/liuyu/github/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma.cpp:180
    #32 0x5597a01ab699 in Local_Orbital_Charge::allocate_gamma(int const&, psi::Psi<double, psi::DEVICE_CPU>*, elecstate::ElecState*) /home/liuyu/github/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma.cpp:267
    #33 0x5597a01b2b58 in Local_Orbital_Charge::allocate_dm_wfc(int const&, elecstate::ElecState*, Local_Orbital_wfc&, psi::Psi<double, psi::DEVICE_CPU>*, psi::Psi<std::complex<double>, psi::DEVICE_CPU>*) /home/liuyu/github/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_charge.cpp:90
    #34 0x5597a002b8ea in ModuleESolver::ESolver_KS_LCAO::beforesolver(int) /home/liuyu/github/abacus-develop/source/module_esolver/esolver_ks_lcao_elec.cpp:166
    #35 0x5597a002ea5f in ModuleESolver::ESolver_KS_LCAO::beforescf(int) /home/liuyu/github/abacus-develop/source/module_esolver/esolver_ks_lcao_elec.cpp:290
    #36 0x55979ff7eb67 in ModuleESolver::ESolver_KS<double, psi::DEVICE_CPU>::Run(int, UnitCell&) /home/liuyu/github/abacus-develop/source/module_esolver/esolver_ks.cpp:187
    #37 0x55979fcf6e26 in Relax_Driver::relax_driver(ModuleESolver::ESolver*) /home/liuyu/github/abacus-develop/source/module_relax/relax_driver.cpp:41
    #38 0x55979fd29a34 in Driver::driver_run() /home/liuyu/github/abacus-develop/source/driver_run.cpp:57
    #39 0x55979fd25b06 in Driver::atomic_world() /home/liuyu/github/abacus-develop/source/driver.cpp:95
    #40 0x55979fd28737 in Driver::init() /home/liuyu/github/abacus-develop/source/driver.cpp:35
    #41 0x55979f8500e4 in main /home/liuyu/github/abacus-develop/source/main.cpp:15
    #42 0x7f279f3e5082 in __libc_start_main ../csu/libc-start.c:308
    #43 0x55979f87b01d in _start (/home/liuyu/github/abacus-develop/build/abacus+0x1c901d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib/prov/librxm-fi.so+0x2e859) in ofi_av_get_addr
==2168342==ABORTING
```

**Comment by Satinelamp** [comment]
I just run this test case in WSL, which seems working fine with one core.

```
alma@DESKTOP-8EH3B7O:~/software/abacus-develop/tests/integrate/308_NO_GO_RE_MB$ abacus

                              ABACUS v3.2

               Atomic-orbital Based Ab-initio Computation at UStc

                     Website: http://abacus.ustc.edu.cn/
               Documentation: https://abacus.deepmodeling.com/
                  Repository: https://github.com/abacusmodeling/abacus-develop
                              https://github.com/deepmodeling/abacus-develop

 Fri May  5 18:13:05 2023
 MAKE THE DIR         : OUT.autotest/
 UNIFORM GRID DIM     : 24 * 24 * 24
 UNIFORM GRID DIM(BIG): 6 * 6 * 6
 DONE(0.0202836  SEC) : SETUP UNITCELL
 DONE(0.055516   SEC) : SYMMETRY
 DONE(0.124318   SEC) : INIT K-POINTS
 ---------------------------------------------------------
 Ion relaxation calculations
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  NBASE
 1       Gamma           1           26
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC
 Si      2s2p1d-8au      13          2
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 -------------------------------------------
 STEP OF ION RELAXATION : 1
 -------------------------------------------
 START CHARGE      : atomic
 DONE(0.460917   SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)
 GE1    -1.972991e+02  0.000000e+00   3.875e-01  2.198e-01
 GE2    -1.971224e+02  1.767439e-01   1.834e-01  8.140e-02
 GE3    -1.971493e+02  -2.694125e-02  1.316e-02  7.452e-02
 GE4    -1.971494e+02  -8.751442e-05  1.253e-03  8.154e-02
 GE5    -1.971494e+02  -1.837915e-05  9.957e-05  8.248e-02
 GE6    -1.971494e+02  -7.814662e-07  9.393e-06  7.671e-02
 GE7    -1.971494e+02  3.098950e-08   1.015e-05  7.849e-02
 GE8    -1.971494e+02  -5.231220e-08  6.427e-07  8.045e-02
 GE9    -1.971494e+02  -8.909310e-09  8.014e-09  7.525e-02
 GE10   -1.971494e+02  3.221671e-11   2.502e-09  8.106e-02
 GE11   -1.971494e+02  1.759472e-11   5.320e-11  7.484e-02
 ETOT DIFF (eV)       : 0.000e+00
 LARGEST GRAD (eV/A)  : 1.595e-01
 BFGS TRUST (Bohr)    : 2.000e-01
 -------------------------------------------
 STEP OF ION RELAXATION : 2
 -------------------------------------------
 DONE(2.337e+00  SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)
 GE1    -1.968302e+02  0.000000e+00   3.806e-02  1.959e-01
 GE2    -1.968385e+02  -8.320038e-03  1.956e-02  7.261e-02
 GE3    -1.968391e+02  -5.763301e-04  2.371e-03  7.834e-02
 GE4    -1.968391e+02  -2.230968e-05  1.081e-04  7.357e-02
 GE5    -1.968391e+02  -3.912315e-08  3.291e-05  7.136e-02
 GE6    -1.968391e+02  1.448534e-08   1.142e-06  8.069e-02
 GE7    -1.968391e+02  7.408804e-09   8.559e-08  7.519e-02
 GE8    -1.968391e+02  -5.986798e-10  4.460e-09  6.963e-02
 GE9    -1.968391e+02  -2.900229e-12  1.117e-09  7.555e-02
 GE10   -1.968391e+02  -4.640366e-12  4.958e-12  7.790e-02

  |CLASS_NAME---------|NAME---------------|TIME(Sec)-----|CALLS----|AVG------|PER%-------
                       total               4.1024         11        0.37      1e+02     %
   Driver              driver_line         4.0944         1         4.1       1e+02     %
   ORB_control         set_orb_tables      0.25845        1         0.26      6.3       %
   ORB_gen_tables      gen_tables          0.25844        1         0.26      6.3       %
   Ions                opt_ions            3.655          1         3.7       89        %
   ESolver_KS_LCAO     Run                 1.9152         2         0.96      47        %
   HSolverLCAO         solve               1.749          21        0.083     43        %
   HamiltLCAO          updateHk            1.1088         21        0.053     27        %
   OperatorLCAO        init                0.26487        42        0.0063    6.5       %
   Nonlocal<LCAO>      contributeHR        0.2009         2         0.1       4.9       %
   LCAO_gen_fixedH     b_NL_beta_new       0.20089        2         0.1       4.9       %
   Veff                contributeHk        0.84339        21        0.04      21        %
   Gint_interface      cal_gint            1.7495         44        0.04      43        %
   Gint_interface      cal_gint_vlocal     0.8398         21        0.04      20        %
   Gint_Tools          cal_psir_ylm        0.1766         1134      0.00016   4.3       %
   OperatorLCAO        get_hs_pointers     1.7675         11        0.16      43        %
   ElecStateLCAO       psiToRho            0.61445        21        0.029     15        %
   Gint_interface      cal_gint_rho        0.60941        21        0.029     15        %
   Force_Stress_LCAO   getForceStress      1.7386         2         0.87      42        %
   Force_LCAO_gamma    ftable_gamma        1.7361         2         0.87      42        %
   Force_LCAO_gamma    allocate_gamma      0.66374        2         0.33      16        %
   LCAO_gen_fixedH     b_NL_mu_new         0.39075        2         0.2       9.5       %
   Force_LCAO_gamma    cal_fvnl_dbeta_new  0.77168        2         0.39      19        %
   Force_LCAO_gamma    cal_fvl_dphi        0.3003         2         0.15      7.3       %
   Gint_interface      cal_gint_force      0.30029        2         0.15      7.3       %
   Gint_Tools          cal_dpsir_ylm       0.15297        54        0.0028    3.7       %
 ----------------------------------------------------------------------------------------

 START  Time  : Fri May  5 18:13:05 2023
 FINISH Time  : Fri May  5 18:13:10 2023
 TOTAL  Time  : 5
 SEE INFORMATION IN : OUT.autotest/
alma@DESKTOP-8EH3B7O:~/software/abacus-develop/tests/integrate/308_NO_GO_RE_MB$
```
