### ISSUE TITLE
ASE-ABACUS interface CANNOT run calculator normally

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#2822]
### Describe the bug

Infomation also in https://gitlab.com/1041176461/ase-abacus/-/issues/16
When I use ASE-ABACUS to run BFGS calculation in NEB example, there is error:
```
Traceback (most recent call last):
  File "/home/james/toys/ASE/init_neb.py", line 58, in <module>
    qn.run() # fmax=0.05
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/site-packages/ase-3.23.0b1-py3.9.egg/ase/optimize/optimize.py", line 273, in run
    return Dynamics.run(self)
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/site-packages/ase-3.23.0b1-py3.9.egg/ase/optimize/optimize.py", line 156, in run
    for converged in Dynamics.irun(self):
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/site-packages/ase-3.23.0b1-py3.9.egg/ase/optimize/optimize.py", line 122, in irun
    self.atoms.get_forces()
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/site-packages/ase-3.23.0b1-py3.9.egg/ase/atoms.py", line 787, in get_forces
    forces = self._calc.get_forces(self)
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/site-packages/ase-3.23.0b1-py3.9.egg/ase/calculators/abc.py", line 30, in get_forces
    return self.get_property('forces', atoms)
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/site-packages/ase-3.23.0b1-py3.9.egg/ase/calculators/calculator.py", line 501, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/site-packages/ase-3.23.0b1-py3.9.egg/ase/calculators/genericfileio.py", line 90, in calculate
    self.template.execute(self.directory, self.profile)
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/site-packages/ase-3.23.0b1-py3.9.egg/ase/calculators/abacus.py", line 133, in execute
    profile.run(directory, self.outputname)
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/site-packages/ase-3.23.0b1-py3.9.egg/ase/calculators/abacus.py", line 32, in run
    check_call(self.argv, stdout=fd, cwd=directory,
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/james/apps/anaconda3/envs/ase-abacus/lib/python3.9/subprocess.py", line 1770, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not int
```

There is How I use ASE-ABACUS in my WSL2
```python
from ase.build import fcc100, add_adsorbate
from ase.constraints import FixAtoms
from ase.optimize import QuasiNewton, BFGS
from pathlib import Path
from ase.io import write
from ase.visualize import view
from ase.calculators.abacus import Abacus, AbacusProfile # abacus interface

import os
os.environ['ABACUS_PP_PATH'] = '/home/james/example/PP'
os.environ['ABACUS_ORBITAL_PATH'] = '/home/james/example/ORB'
print(os.environ.get('ABACUS_PP_PATH'))
print(os.environ.get('ABACUS_ORBITAL_PATH'))

# https://wiki.fysik.dtu.dk/ase/tutorials/neb/diffusion.html

# 2x2-Al(001) surface with 3 layers and an
# Au atom adsorbed in a hollow site:
slab = fcc100('Al', size=(2, 2, 3),periodic=True)

add_adsorbate(slab, 'Au', 1.7, 'hollow')
slab.center(axis=2, vacuum=4.0)

# Make sure the structure is correct:
# view(slab)

# Fix second and third layers:
mask = [atom.tag > 1 for atom in slab]
# print(mask)
slab.set_constraint(FixAtoms(mask=mask))

pp = {'Al':'Al_ONCV_PBE-1.0.upf','Au':'Au_ONCV_PBE-1.0.upf'}
#write('./POSCAR_init.vasp', images=slab, format='vasp')
write('STRU', images=slab, format='abacus', pp=pp)

# Use ABACUS
abacus='/home/james/apps/abacus/latest/bin/abacus' # you abacus pathway
ncore = 8
profile = AbacusProfile(argv=['mpirun','-n',ncore,abacus])
kpts = [1,1,1] # KPOINTS setting
# calculation setting for abacus using pw
slab.calc = Abacus(profile=profile, ntype=2, ecutwfc=20, scf_nmax=50, 
            smearing_method='gaussian', smearing_sigma=0.01, basis_type='pw', 
            mixing_type='pulay', mixing_beta='0.7', scf_thr=1e-8, out_chg=1, calculation='scf', force_thr=0.001, stress_thr=5,
            cal_force=1, cal_stress=1, out_stru=1, pp=pp, kpts=kpts)

# calculation setting for abacus using lcao
# orb = {'Al':'Al_gga_8au_100Ry_2s2p1d.orb','Au':'Au_gga_8au_100Ry_2s2p1d.orb'}
# slab.calc = Abacus(profile=profile, ntype=2, ecutwfc=20, scf_nmax=50, 
#             smearing_method='gaussian', smearing_sigma=0.01, basis_type='lcao', 
#             mixing_type='pulay', mixing_beta='0.7', scf_thr=1e-8, out_chg=1, calculation='scf', force_thr=0.001, stress_thr=5,
#             cal_force=1, cal_stress=1, out_stru=1, pp=pp, basis=orb, kpts=kpts)

# Initial state:
#qn = QuasiNewton(slab, trajectory='initial.traj')
qn = BFGS(slab, trajectory='initial.traj')
qn.run() # fmax=0.05

# Final state:
slab[-1].x += slab.get_cell()[0, 0] / 2
write('STRU', images=slab, format='abacus', pp=pp)
#write('./POSCAR_final.vasp', images=slab, format='vasp')
#qn = QuasiNewton(slab, trajectory='final.traj')
qn = BFGS(slab, trajectory='final.traj')
qn.run() # fmax=0.05
```

### Expected behavior

ASE calculator run BFGS with ABACUS normally

### To Reproduce

ABACUS 3.3.1
Python 3.11
ASE-ABACUS interface in https://gitlab.com/1041176461/ase-abacus
installed by 
```
conda create -n ase-abacus
conda activate ase-abacus
python setup.py install
```

**Comment by QuantumMisaka** [comment]
solved in https://gitlab.com/1041176461/ase-abacus/-/issues/16
