### ISSUE TITLE
BUG: force and stress CANNOT be read from interfaces in v3.4.1 ABACUS

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3116]
### Describe the bug

As #3067 , the force and stress print-out is formatting by refactored print_* functions with new formatter library by @kirk0830 .

That's very good, but some interface do not follow up, which cannot read forces and stress information from ABACUS output file `running*.log`

Like ASE-ABACUS interfaces @1041176461 
```python
In [1]: from ase.io import read
In [2]: result = read("running_scf.log", format='abacus-out')

In [3]: result.get_forces()
---------------------------------------------------------------------------
PropertyNotImplementedError               Traceback (most recent call last)
Cell In[3], line 1
----> 1 result.get_forces()

File ~/apps/miniconda3/envs/ase/lib/python3.10/site-packages/ase/atoms.py:787, in Atoms.get_forces(self, apply_constraint, md)
    785 if self._calc is None:
    786     raise RuntimeError('Atoms object has no calculator.')
--> 787 forces = self._calc.get_forces(self)
    789 if apply_constraint:
    790     # We need a special md flag here because for MD we want
    791     # to skip real constraints but include special "constraints"
    792     # Like Hookean.
    793     for constraint in self.constraints:

File ~/apps/miniconda3/envs/ase/lib/python3.10/site-packages/ase/calculators/abc.py:30, in GetPropertiesMixin.get_forces(self, atoms)
     29 def get_forces(self, atoms=None):
---> 30     return self.get_property('forces', atoms)

File ~/apps/miniconda3/envs/ase/lib/python3.10/site-packages/ase/calculators/singlepoint.py:49, in SinglePointCalculator.get_property(self, name, atoms, allow_calculation)
     47 if name not in self.results or self.check_state(atoms):
     48     if allow_calculation:
---> 49         raise PropertyNotImplementedError(
     50             'The property "{0}" is not available.'.format(name))
     51     return None
     53 result = self.results[name]

PropertyNotImplementedError: The property "forces" is not available.

In [6]: result
Out[6]: Atoms(symbols='C37H2Fe80O', pbc=True, cell=[[9.97966, 0.0, 0.0], [0.0, 19.6401, 0.0], [-0.763947, 0.0, 12.6616]], initial_magmoms=..., momenta=..., calculator=SinglePointDFTCalculator(...))

In [11]: result.get_total_energy()
Out[11]: -263809.35346

In [12]: result.get_magnetic_moment()
Out[12]: 143.511

In [14]: result.get_stress()
---------------------------------------------------------------------------
PropertyNotImplementedError               Traceback (most recent call last)
Cell In[14], line 1
----> 1 result.get_stress()

File ~/apps/miniconda3/envs/ase/lib/python3.10/site-packages/ase/atoms.py:819, in Atoms.get_stress(self, voigt, apply_constraint, include_ideal_gas)
    816 if self._calc is None:
    817     raise RuntimeError('Atoms object has no calculator.')
--> 819 stress = self._calc.get_stress(self)
    820 shape = stress.shape
    822 if shape == (3, 3):
    823     # Convert to the Voigt form before possibly applying
    824     # constraints and adding the dynamic part of the stress
    825     # (the "ideal gas contribution").

File ~/apps/miniconda3/envs/ase/lib/python3.10/site-packages/ase/calculators/abc.py:33, in GetPropertiesMixin.get_stress(self, atoms)
     32 def get_stress(self, atoms=None):
---> 33     return self.get_property('stress', atoms)

File ~/apps/miniconda3/envs/ase/lib/python3.10/site-packages/ase/calculators/singlepoint.py:49, in SinglePointCalculator.get_property(self, name, atoms, allow_calculation)
     47 if name not in self.results or self.check_state(atoms):
     48     if allow_calculation:
---> 49         raise PropertyNotImplementedError(
     50             'The property "{0}" is not available.'.format(name))
     51     return None
     53 result = self.results[name]

PropertyNotImplementedError: The property "stress" is not available.
```

And abacustest @pxlxingliang 
```
(ase) [2201110432@wm2-login01 run_BFGS_noinit]$ abacustest collectdata -j . -p ~/example/abacus/param.json 
Read the parameters from /lustre/home/2201110432/example/abacus/param.json
Handle .
ERROR: excecute function Abacus.GetForceStessFromLog() failed, skip it!
Traceback (most recent call last):
  File "/lustre/home/2201110432/apps/miniconda3/envs/ase/lib/python3.10/site-packages/abacustest/lib_collectdata/result.py", line 62, in __getitem__
    func(self)
  File "/lustre/home/2201110432/apps/miniconda3/envs/ase/lib/python3.10/site-packages/abacustest/lib_collectdata/abacus/abacus.py", line 187, in GetForceStessFromLog
    stress.append(float(m))
ValueError: could not convert string to float: '----------------------------------------------------------------'
WARNING: try to catch the value of 'force' by Abacus.GetForceStessFromLog(), but failed
ERROR: excecute function Abacus.GetForceStessFromLog() failed, skip it!
Traceback (most recent call last):
  File "/lustre/home/2201110432/apps/miniconda3/envs/ase/lib/python3.10/site-packages/abacustest/lib_collectdata/result.py", line 62, in __getitem__
    func(self)
  File "/lustre/home/2201110432/apps/miniconda3/envs/ase/lib/python3.10/site-packages/abacustest/lib_collectdata/abacus/abacus.py", line 187, in GetForceStessFromLog
    stress.append(float(m))
ValueError: could not convert string to float: '----------------------------------------------------------------'
WARNING: try to catch the value of 'stress' by Abacus.GetForceStessFromLog(), but failed
Write the results to result.json
                                             version  natom        kpt  ibzk  \
.  v3.4.1(77f178d04 (Thu Oct 26 11:32:59 2023 +08...    120  [3, 1, 2]     4   

                                        element_list   nelec  normal_end  \
.  [H, H, C, C, C, C, C, C, C, C, C, C, C, C, C, ...  1436.0        True   

   converge  scf_steps relax_converge  relax_steps  total_mag  absolute_mag  \
.      True         79           None            1    143.511       156.616   

         energy force stress  band_gap    efermi  ncore  total_time  scf_time  \
. -263809.35346  None   None   0.00861  5.675739     16     946.953     918.1   

  force_time  stress_time INPUT/ks_solver  INPUT/mixing_beta  INPUT/scf_thr  \
.       None     22.75394         genelpa                -10        0.00001   

   INPUT/force_thr_ev INPUT/relax_method  
.            0.025711                 cg  
```

This problem will cause confusion for users

### Expected behavior

The forces and stress information should be read properly by ASE-ABACUS interface, abacus-test, and other existing interfaces, which do not keep up with the new formatter resolution.

### To Reproduce

read `running*.log` file by interfaces, then check the forces and stress result

one example:

[running_scf.log](https://github.com/deepmodeling/abacus-develop/files/13194507/running_scf.log)

### Environment

- ABACUS 3.4.1 Commit: 77f178d04 (Thu Oct 26 11:32:59 2023 +0800)
- ASE 3.23.0b1
- ASE-ABACUS interfaces: c05be56556048001768effd50596319f36185c6e
- abacus-test: v0.1.0

### Additional Context

The formatter tools should be widely used in next developing, at the same time, the change should be widely known and keep-up 

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [X] Environment details.
- [X] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by 1041176461** [comment]
I fixed this bug in ASE-ABACUS interface ( commit: https://gitlab.com/1041176461/ase-abacus/-/commit/6022661a1370706adb071c7d51325d3e4c021009)

**Comment by QuantumMisaka** [comment]
> I fixed this bug in ASE-ABACUS interface ( commit: https://gitlab.com/1041176461/ase-abacus/-/commit/6022661a1370706adb071c7d51325d3e4c021009)

Good! Now ase-abacus interfaces can read forces and stress properly from running*.log from v3.4.0 and v3.4.1

**Comment by pxlxingliang** [comment]
This is fixed in develop branch of abacustest now! https://github.com/pxlxingliang/abacus-test/tree/develop

**Comment by QuantumMisaka** [comment]
Waiting for automated interfaces test
