### ISSUE TITLE
"SIGNAL: 9" ERROR when running LCAO job with ks_solver "elpa" on E5 CPU

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3351]
### Describe the bug

In Bohrium, I use c32_m64_cpu to run LCAO job (ks_solver=elpa), sometimes the job will be scheduled to "E5-2682 v4" cpu, and will suffer the error:
```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 39 RUNNING AT dp-lbg-471-10150017
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
```
The cpu "8269CY" can run elpa job successfully.

The abacustest job: https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-intel-elpa-2a4aaf

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by Zhuxuegang2022** [comment]
```
#0  0x00007ffff7f91f66 in double_hh_trafo_complex_AVX_2hv_double () from /home/zxg/anaconda3/envs/abacus3.4.4/bin/../lib/libelpa_openmp.so.17
#1  0x00007ffff7e8fa8b in compute_hh_trafo::compute_hh_trafo_complex_openmp_double (obj=..., usegpu=<optimized out>, wantdebug=<optimized out>, 
    a=<error reading variable: value requires 727040 bytes, which is more than max-value-size>, a_dev=<optimized out>, stripe_width=4, a_dim2=284, stripe_count=1, max_threads=40, l_nev=75, a_off=0, 
    nbw=32, max_blk_size=252, bcast_buffer=..., bcast_buffer_dev=93825044783424, hh_tau_dev=252, kernel_flops=0, kernel_time=1.1399993127270136e-07, n_times=1, off=0, ncols=252, istripe=1, 
    my_thread=14, thread_width=2, kernel=9, last_stripe_width=<error reading variable: Cannot access memory at address 0x0>) at ../src/elpa2/compute_hh_trafo.F90:1530
#2  0x00007ffff7eb8f25 in __elpa2_compute_MOD_trans_ev_tridi_to_band_complex_double._omp_fn.8 () at ../src/elpa2/elpa2_trans_ev_tridi_to_band_template.F90:2636
#3  0x00007fffea9ec6d9 in gomp_thread_start (xdata=<optimized out>) at ../../../libgomp/team.c:129
#4  0x00007fffddb2fac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007fffddbc1660 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
![image](https://github.com/deepmodeling/abacus-develop/assets/121375968/01ceef71-bd9c-4566-ac1d-dd1b51aa7afb)
Instruction 'vfnmadd132sd' {FMA\|AVX512_F}.
Looks like this CPU do not support the FMA instruction set. This might be a bug of ELPA.
My `/proc/cpuinfo`:
```
model name	: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm arat pln pts md_clear flush_l1d
```

`ELPA_DEFAULT_real_kernel=ELPA_2STAGE_REAL_SSE_BLOCK2 ELPA_DEFAULT_complex_kernel=ELPA_2STAGE_COMPLEX_SSE_BLOCK2 OMP_NUM_THREADS=1 gdb abacus`:

```
Thread 1 "abacus" received signal SIGILL, Illegal instruction.
0x00007ffff7f90a17 in double_hh_trafo_complex_SSE_2hv_double () from /home/zxg/anaconda3/envs/abacus3.4.4/bin/../lib/libelpa_openmp.so.17
(gdb) where
#0  0x00007ffff7f90a17 in double_hh_trafo_complex_SSE_2hv_double () from /home/zxg/anaconda3/envs/abacus3.4.4/bin/../lib/libelpa_openmp.so.17
#1  0x00007ffff7e8f8eb in compute_hh_trafo::compute_hh_trafo_complex_openmp_double (obj=..., usegpu=<optimized out>, wantdebug=<optimized out>, 
    a=<error reading variable: value requires 345344 bytes, which is more than max-value-size>, a_dev=<optimized out>, stripe_width=76, a_dim2=284, stripe_count=1, max_threads=1, l_nev=75, a_off=0, 
    nbw=32, max_blk_size=252, bcast_buffer=..., bcast_buffer_dev=93825044672752, hh_tau_dev=252, kernel_flops=0, kernel_time=2.4700011636014096e-07, n_times=1, off=0, ncols=252, istripe=1, 
    my_thread=1, thread_width=75, kernel=7, last_stripe_width=<error reading variable: Cannot access memory at address 0x0>) at ../src/elpa2/compute_hh_trafo.F90:1291
#2  0x00007ffff7eb8f25 in __elpa2_compute_MOD_trans_ev_tridi_to_band_complex_double._omp_fn.8 () at ../src/elpa2/elpa2_trans_ev_tridi_to_band_template.F90:2636
#3  0x00007fffea9e7583 in GOMP_parallel (fn=0x7ffff7eb8e40 <__elpa2_compute_MOD_trans_ev_tridi_to_band_complex_double._omp_fn.8>, data=0x7fffffffc260, num_threads=1, flags=0)
    at ../../../libgomp/parallel.c:178
#4  0x00007ffff7ec53b9 in elpa2_compute::trans_ev_tridi_to_band_complex_double (obj=..., na=252, nev=75, nblk=1, nbw=32, q=..., ldq=252, matrixcols=252, 
    hh_trans=<error reading variable: value requires 573440 bytes, which is more than max-value-size>, mpi_comm_rows=-1006632957, mpi_comm_cols=-1006632956, wantdebug=.FALSE., usegpu=.FALSE., 
    max_threads=1, success=.TRUE., kernel=7) at ../src/elpa2/elpa2_trans_ev_tridi_to_band_template.F90:2626
#5  0x00007ffff7f2de6e in elpa2_impl::elpa_solve_evp_complex_2stage_all_host_arrays_double_impl (obj=..., aextern=..., evextern=..., qextern=...) at ../src/elpa2/elpa2_template.F90:1327
#6  0x00007ffff7e80c88 in elpa_impl::elpa_eigenvectors_all_host_arrays_dc (self=..., a=..., ev=..., q=..., error=32767) at ../src/elpa_impl_math_template.F90:126
#7  0x00007ffff7e85daa in elpa_impl::elpa_eigenvectors_all_host_arrays_dc_c (handle=<optimized out>, a_p=<optimized out>, ev_p=<optimized out>, q_p=<optimized out>, error=32767)
    at ../src/elpa_impl_math_template.F90:311
#8  0x0000555555aec576 in ELPA_Solver::eigenvector(std::complex<double>*, double*, std::complex<double>*) ()
#9  0x0000555555aed741 in ELPA_Solver::generalized_eigenvector(std::complex<double>*, std::complex<double>*, int&, double*, std::complex<double>*) ()
#10 0x00005555557dc9d1 in hsolver::DiagoElpa<std::complex<double> >::diag(hamilt::Hamilt<std::complex<double>, psi::DEVICE_CPU>*, psi::Psi<std::complex<double>, psi::DEVICE_CPU>&, double*) ()
#11 0x00005555557d452e in hsolver::HSolverLCAO<std::complex<double> >::hamiltSolvePsiK(hamilt::Hamilt<std::complex<double>, psi::DEVICE_CPU>*, psi::Psi<std::complex<double>, psi::DEVICE_CPU>&, double*) ()
#12 0x00005555557d490d in hsolver::HSolverLCAO<std::complex<double> >::solveTemplate(hamilt::Hamilt<std::complex<double>, psi::DEVICE_CPU>*, psi::Psi<std::complex<double>, psi::DEVICE_CPU>&, elecstate::ElecState*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) ()
#13 0x00005555557d50bd in hsolver::HSolverLCAO<std::complex<double> >::solve(hamilt::Hamilt<std::complex<double>, psi::DEVICE_CPU>*, psi::Psi<std::complex<double>, psi::DEVICE_CPU>&, elecstate::ElecState*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) ()
#14 0x000055555592c3a2 in ModuleESolver::ESolver_KS_LCAO<std::complex<double>, double>::hamilt2density(int, int, double) ()
#15 0x000055555587d8be in ModuleESolver::ESolver_KS<std::complex<double>, psi::DEVICE_CPU>::Run(int, UnitCell&) ()
#16 0x00005555557912b4 in Relax_Driver<double, psi::DEVICE_CPU>::relax_driver(ModuleESolver::ESolver*) ()
#17 0x00005555557a3047 in Driver::driver_run() ()
#18 0x00005555557a21aa in Driver::atomic_world() ()
#19 0x00005555557a2b3a in Driver::init() ()
#20 0x00005555555b2eb7 in main ()
```

**Comment by caic99** [comment]
These CPUs are too old to support the modern instruction sets, like FMA. It is neither possible nor efficient to maintain such forward compatibility. 
For the users who are facing problems using the pre-built version of ABACUS, we recommend switching to the scalapack solver, or compiling ELPA natively from source code.

**Comment by hongriTianqi** [comment]
This issue has been given content replies. So will be closed.
