### ISSUE TITLE
Error on using cusolver

### ISSUE THREAD

**Issue by caic99** [deepmodeling/abacus-develop#3424]
### Describe the bug

ABACUS crashes when using cuSolver as the `ks_solver`.

```text
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
free(): invalid pointer
```

And, the availability of using `cusolver` as an option of `ks_solver` is not updated in the docs.

### To Reproduce

[test case](https://hpc-profiling-example.oss-cn-beijing.aliyuncs.com/example/abacus/water_scan0_test.zip), and set `ks_solver cusolver` in the `INPUT_deepks` file
Command used: `OMP_NUM_THREADS=1 mpirun -n 4 abacus`

### Environment

Conda is used to deploy the CUDA-supported version of abacus.
`abacus                    3.5.0           cuda_mpi_mpich_h9c0ec5b_1    conda-forge`

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by caic99** [comment]
```
(gdb) where
#0  0x00007fff332b3594 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#1  0x00007fff333a02ba in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fff334d3abb in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fff335f9109 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fff33274833 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007fff335ef3a1 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007fff33270450 in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#7  0x00007fff334413ae in ?? () from /lib/x86_64-linux-gnu/libcuda.so.1
#8  0x00007ffff7a465c1 in ?? ()
   from /opt/conda/envs/abacus/bin/../lib/libcudart.so.12
#9  0x00007ffff7a17eda in ?? ()
   from /opt/conda/envs/abacus/bin/../lib/libcudart.so.12
#10 0x00007ffff7a6b8d9 in cudaMemcpy ()
   from /opt/conda/envs/abacus/bin/../lib/libcudart.so.12
#11 0x0000555555841bd5 in Diag_Cusolver_gvd::Dngvd_double(int, int, double*, double*, double*, double*) ()
#12 0x00005555558426d9 in hsolver::DiagoCusolver<double>::diag(hamilt::Hamilt<double, psi::DEVICE_CPU>*, psi::Psi<double, psi::DEVICE_CPU>&, double*) ()
#13 0x000055555583164e in hsolver::HSolverLCAO<double>::hamiltSolvePsiK(hamilt::Hamilt<double, psi::DEVICE_CPU>*, psi::Psi<double, psi::DEVICE_CPU>&, double*)
    ()
#14 0x0000555555831a2d in hsolver::HSolverLCAO<double>::solveTemplate(hamilt::Hamilt<double, psi::DEVICE_CPU>*, psi::Psi<double, psi::DEVICE_CPU>&, elecstate::ElecState*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) ()
#15 0x000055555583232d in hsolver::HSolverLCAO<double>::solve(hamilt::Hamilt<double, psi::DEVICE_CPU>*, psi::Psi<double, psi::DEVICE_CPU>&, elecstate::ElecState*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) ()
#16 0x00005555559e97b2 in ModuleESolver::ESolver_KS_LCAO<double, double>::hamilt2density(int, int, double) ()
#17 0x000055555593268e in ModuleESolver::ESolver_KS<double, psi::DEVICE_CPU>::Run(int, UnitCell&) ()
#18 0x00005555557c6d84 in Relax_Driver<double, psi::DEVICE_CPU>::relax_driver(ModuleESolver::ESolver*) ()
#19 0x00005555557d8b57 in Driver::driver_run() ()
#20 0x00005555557d7cba in Driver::atomic_world() ()
#21 0x00005555557d864a in Driver::init() ()
#22 0x00005555555bb097 in main ()
```
