### ISSUE TITLE
assert(psi_norm>0) error with ks_solver dav

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4068]
### Describe the bug

I have some cases suffer below error:
```
Traceback (most recent call last):
  File "/home/input_lbg-471-12232015/tmp/inputs/artifacts/dflow_python_packages/opt/mamba/lib/python3.10/site-packages/dflow/python/utils.py", line 337, in try_to_execute
    output = op_obj.execute(input)
  File "/home/input_lbg-471-12232015/tmp/inputs/artifacts/dflow_python_packages/opt/mamba/lib/python3.10/site-packages/dflow/python/op.py", line 136, in wrapper_exec
    op_out = func(self, op_in)
  File "/home/input_lbg-471-12232015/tmp/inputs/artifacts/dflow_python_packages/opt/mamba/lib/python3.10/site-packages/fpop/run_fp.py", line 170, in execute
    backward_dir_name = self.run_task(backward_dir_name,log_name,backward_list,run_image_config,optional_input)
  File "/home/input_lbg-471-12232015/tmp/inputs/artifacts/dflow_python_packages/opt/mamba/lib/python3.10/site-packages/fpop/abacus.py", line 637, in run_task
    raise TransientError(
dflow.python.python_op_template.TransientError: ('abacus failed\n', 'out msg', '', '\n', 'err msg', "WARNING: Total thread number on this node mismatches with hardware availability. This may cause poor performance.\nInfo: Local MPI proc number: 16,OpenMP thread number: 1,Total thread number: 16,Local thread limit: 32\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\nabacus: /abacus-develop/source/module_hsolver/diago_david.cpp:934: void hsolver::DiagoDavid<>::SchmitOrth(const int &, const int, const int, psi::Psi<T, Device> &, const T *, T *, const int, const int) [T = std::complex<double>, Device = psi::DEVICE_CPU]: Assertion `psi_norm > 0.0' failed.\n", '\n')
```

[V.zip](https://github.com/deepmodeling/abacus-develop/files/15145971/V.zip)
[Cu.zip](https://github.com/deepmodeling/abacus-develop/files/15146007/Cu.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@haozhihan could you have a look?

**Comment by haozhihan** [comment]
https://github.com/deepmodeling/abacus-develop/issues/3643 FYI

**Comment by WHUweiqingzhou** [comment]
So, you do not think it is a bug for old dav method?

**Comment by haozhihan** [comment]
I think, this should be a numerical problem for Schmidt orthogonalization, not a bug for old `dav`. 

Currently, Schmidt orthogonalization is used in both the `cg` and `dav` methods of abacus, which leads to this issue.

**Comment by pxlxingliang** [comment]
More examples that suffer this error.
[relaxation.zip](https://github.com/deepmodeling/abacus-develop/files/15159364/relaxation.zip)

**Comment by WHUweiqingzhou** [comment]
@mohanchen and @dyzheng,
what is your opinion? Could we just leave this issue as a feature instead of a bug.

**Comment by dyzheng** [comment]
I think it is not a bug, often caused by accuracy loss for Schmidt orthogonalization method.

**Comment by haozhihan** [comment]
> More examples that suffer this error. [relaxation.zip](https://github.com/deepmodeling/abacus-develop/files/15159364/relaxation.zip)

@pxlxingliang Can you provide related input files instead of just log and OUTPUT?

**Comment by pxlxingliang** [comment]
> > More examples that suffer this error. [relaxation.zip](https://github.com/deepmodeling/abacus-develop/files/15159364/relaxation.zip)
> 
> @pxlxingliang Can you provide related input files instead of just log and OUTPUT?

Please check the attached file of V inputs
[v.zip](https://github.com/deepmodeling/abacus-develop/files/15243015/v.zip)
