### ISSUE TITLE
LDOS calculation is needed

### ISSUE THREAD

**Issue by Luc1anoo** [deepmodeling/abacus-develop#4192]
### Background

I'm tring to perform STM calculation using [ASE.STM module](https://wiki.fysik.dtu.dk/ase/ase/dft/stm.html). I have done the calculation using GPAW as calculator. When I try to change the calculator to ABACUS, the error thrown:
Traceback (most recent call last):
  File "/personal/ABACUS-cases/10/stm_ABACUS/stm_ABACUS.py", line 72, in <module>
    x, y, I = stm.scan2(bias=bias, z=height, repeat=(5,5))
  File "/opt/mamba/lib/python3.10/site-packages/ase/dft/stm.py", line 163, in scan2
    self.calculate_ldos(bias)
  File "/opt/mamba/lib/python3.10/site-packages/ase/dft/stm.py", line 68, in calculate_ldos
    ldos = np.zeros(calc.get_pseudo_wave_function(0, 0, 0).shape)
AttributeError: 'Abacus' object has no attribute 'get_pseudo_wave_function'

I checked the source code of ASE.STM ([Source code for ase.dft.stm](https://wiki.fysik.dtu.dk/ase/_modules/ase/dft/stm.html#STM)) and found that the error may be due to the lack of LDOS calculation feature in ABACUS.

### Describe the solution you'd like

Add LDOS calculation feature.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
also see #3665

**Comment by kirk0830** [comment]
this feature has been implemented by @YuLiu98 in PR #6100, #6109 and #6123
