### ISSUE TITLE
Segment fault when `exx_ccp_rmesh_time` is large

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#4530]
### Describe the bug

The segment fault is located to the construction of the radial interpolation table.
I doubt that it is related to the recent refactor of `GlobalC::ORB`.

```
Program received signal SIGSEGV, Segmentation fault.
_ZN13ORB_table_phi14cal_ST_Phi12_RERKiS1_RK20Numerical_Orbital_LmS4_S1_PdS5_PKN10ModuleBase20Sph_Bessel_Recursive2D2E.extracted(void) () at /home/fortneu49/abacus-fix/abacus-develop/source/module_basis/module_ao/ORB_table_phi.cpp:210
210                 integrated_func[ik] = jl_r[ik] * k1_dot_k2[ik];
```

gdb backtrace info:
```
#5  0x0000000000a133ab in ORB_table_phi::cal_ST_Phi12_R (job=<optimized out>, 
    l=<optimized out>, n1=..., n2=..., rmesh=@0x7fffffffb990: 3609, rs=0x1e083880, 
    drs=0x1e08a950, psb=0x2e14950)
    at /home/fortneu49/abacus-fix/abacus-develop/source/module_basis/module_ao/ORB_table_phi.cpp:202
#6  0x00000000009ea428 in Center2_Orb::Orb11::init_radial_table (this=0x2e677d48)
    at /home/fortneu49/abacus-fix/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb11.cpp:39
--Type <RET> for more, q to quit, c to continue without paging--
#7  0x0000000000abd266 in Matrix_Orbs11::init_radial_table (this=<optimized out>)
    at /home/fortneu49/abacus-fix/abacus-develop/source/module_ri/Matrix_Orbs11.cpp:101
#8  0x00000000008521de in LRI_CV<double>::set_orbitals (this=this@entry=0x2d4ab80, 
    lcaos_in=std::vector of length 1, capacity 1 = {...}, 
    abfs_in=std::vector of length 1, capacity 1 = {...}, 
    abfs_ccp_in=std::vector of length 1, capacity 1 = {...}, 
    kmesh_times=@0x2cd7c88: 4, ccp_rmesh_times_in=<optimized out>)
    at /home/fortneu49/abacus-fix/abacus-develop/source/module_ri/LRI_CV.hpp:63
```

### To Reproduce

Run tests/integrate/281_NO_KP_HSE with `exx_ccp_rmesh_times` set to 5.

**Comment by maki49** [comment]
It have been fixed by #4516 .
