### ISSUE TITLE
Bug: buffer-overflow in `207_NO_KP_OXC`

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#4545]
### Describe the bug

When i run `207_NO_KP_OXC` with `ASAN=ON`:
```
root@bohrium-13341-1152930:~/abacus-develop/tests/integrate/207_NO_KP_OXC# abacus 
                                                                                     
                              ABACUS v3.7.0

               Atomic-orbital Based Ab-initio Computation at UStc                    

                     Website: http://abacus.ustc.edu.cn/                             
               Documentation: https://abacus.deepmodeling.com/                       
                  Repository: https://github.com/abacusmodeling/abacus-develop       
                              https://github.com/deepmodeling/abacus-develop         
                      Commit: 8942b4776 (Tue Jul 2 15:05:11 2024 +0800)

 Wed Jul  3 13:24:55 2024
 MAKE THE DIR         : OUT.autotest/
 RUNNING WITH DEVICE  : CPU / Intel(R) Xeon(R) Platinum
 dft_functional readin is: hse
 dft_functional in pseudopot file is: PBE
 Please make sure this is what you need
 UNIFORM GRID DIM        : 24 * 24 * 24
 UNIFORM GRID DIM(BIG)   : 6 * 6 * 6
 DONE(0.0774562  SEC) : SETUP UNITCELL
 DONE(0.0779771  SEC) : INIT K-POINTS
 ---------------------------------------------------------
 Self-consistent calculations for electrons
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  NBASE       
 1       2               1           26          
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC          
 Si      2s2p1d-8au      13          2           
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(0.0996413  SEC) : INIT PLANEWAVE
=================================================================
==2470==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x611000e1ff28 at pc 0x56104b5c2daa bp 0x7fffad4bfe40 sp 0x7fffad4bfe30
READ of size 8 at 0x611000e1ff28 thread T0
    #0 0x56104b5c2da9 in std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >::operator[](unsigned long) const /usr/include/c++/11/bits/stl_vector.h:1064
    #1 0x56104b5c2da9 in Center2_Orb::cal_ST_Phi12_R(int const&, int const&, Numerical_Orbital_Lm const&, Numerical_Orbital_Lm const&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&, double*, double*, ModuleBase::Sph_Bessel_Recursive::D2 const*) /root/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/center2_orb.cpp:359
    #2 0x56104b5cb934 in Center2_Orb::Orb11::init_radial_table(std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&) /root/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb11.cpp:72
    #3 0x56104b5d0c62 in Center2_Orb::Orb21::init_radial_table(std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> > const&) /root/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb21.cpp:96
    #4 0x56104b8a49b3 in Matrix_Orbs21::init_radial_table(std::map<unsigned long, std::map<unsigned long, std::set<double, std::less<double>, std::allocator<double> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::set<double, std::less<double>, std::allocator<double> > > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<unsigned long, std::set<double, std::less<double>, std::allocator<double> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::set<double, std::less<double>, std::allocator<double> > > > > > > > const&) /root/abacus-develop/source/module_ri/Matrix_Orbs21.cpp:147
    #5 0x56104b934410 in ABFs_Construct::PCA::cal_PCA(std::vector<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > >, std::allocator<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > > > > const&, std::vector<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > >, std::allocator<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > > > > const&, double) /root/abacus-develop/source/module_ri/ABFs_Construct-PCA.cpp:98
    #6 0x56104b90755a in Exx_Abfs::Construct_Orbs::pca(std::vector<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > >, std::allocator<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > > > > const&, std::vector<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > >, std::allocator<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > > > > const&, double, double) /root/abacus-develop/source/module_ri/exx_abfs-construct_orbs.cpp:266
    #7 0x56104b911b46 in Exx_Abfs::Construct_Orbs::abfs_same_atom(std::vector<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > >, std::allocator<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > > > > const&, double, double) /root/abacus-develop/source/module_ri/exx_abfs-construct_orbs.cpp:101
    #8 0x56104b0c3028 in Exx_LRI<double>::init(ompi_communicator_t* const&, K_Vectors const&) /root/abacus-develop/source/module_ri/Exx_LRI.hpp:59
    #9 0x56104b137b6f in ModuleESolver::ESolver_KS_LCAO<std::complex<double>, double>::before_all_runners(Input&, UnitCell&) /root/abacus-develop/source/module_esolver/esolver_ks_lcao.cpp:204
    #10 0x56104a99a6e0 in Driver::driver_run() /root/abacus-develop/source/driver_run.cpp:46
    #11 0x56104a9974ee in Driver::atomic_world() /root/abacus-develop/source/driver.cpp:116
    #12 0x56104a999e00 in Driver::init() /root/abacus-develop/source/driver.cpp:37
    #13 0x561049d360c2 in main /root/abacus-develop/source/main.cpp:39
    #14 0x7ff7b56a5d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #15 0x7ff7b56a5e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #16 0x561049d72d14 in _start (/usr/local/bin/abacus+0x29cd14)

0x611000e1ff28 is located 24 bytes to the left of 240-byte region [0x611000e1ff40,0x611000e20030)
allocated by thread T0 here:
    #0 0x7ff7d06f11e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x56104a2c83e8 in __gnu_cxx::new_allocator<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > >::allocate(unsigned long, void const*) /usr/include/c++/11/ext/new_allocator.h:127
    #2 0x56104a2c83e8 in std::allocator_traits<std::allocator<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > > >::allocate(std::allocator<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > >&, unsigned long) /usr/include/c++/11/bits/alloc_traits.h:464
    #3 0x56104a2c83e8 in std::_Vector_base<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, std::allocator<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > > >::_M_allocate(unsigned long) /usr/include/c++/11/bits/stl_vector.h:346
    #4 0x56104a2c83e8 in std::vector<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, std::allocator<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > > >::_M_default_append(unsigned long) /usr/include/c++/11/bits/vector.tcc:635
    #5 0x56104a2c68ea in std::vector<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, std::allocator<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > > >::resize(unsigned long) /usr/include/c++/11/bits/stl_vector.h:940
    #6 0x56104a2c68ea in ModuleBase::Sph_Bessel_Recursive::D2::cal_jlx_0(int, unsigned long, unsigned long) /root/abacus-develop/source/module_base/sph_bessel_recursive-d2.cpp:42
    #7 0x56104a2c79bc in ModuleBase::Sph_Bessel_Recursive::D2::cal_jlx(int, unsigned long, unsigned long) /root/abacus-develop/source/module_base/sph_bessel_recursive-d2.cpp:33
    #8 0x56104b5c3b3e in Center2_Orb::init_Table_Spherical_Bessel(int, int, int&, int&, int const&, int, int, double, double, int, int, ModuleBase::Sph_Bessel_Recursive::D2*&) /root/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/center2_orb.cpp:134
    #9 0x56104b8a0ac7 in Matrix_Orbs21::init(int, double, double) /root/abacus-develop/source/module_ri/Matrix_Orbs21.cpp:31
    #10 0x56104b933709 in ABFs_Construct::PCA::cal_PCA(std::vector<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > >, std::allocator<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > > > > const&, std::vector<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > >, std::allocator<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > > > > const&, double) /root/abacus-develop/source/module_ri/ABFs_Construct-PCA.cpp:92
    #11 0x56104b90755a in Exx_Abfs::Construct_Orbs::pca(std::vector<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > >, std::allocator<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > > > > const&, std::vector<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > >, std::allocator<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > > > > const&, double, double) /root/abacus-develop/source/module_ri/exx_abfs-construct_orbs.cpp:266
    #12 0x56104b911b46 in Exx_Abfs::Construct_Orbs::abfs_same_atom(std::vector<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > >, std::allocator<std::vector<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> >, std::allocator<std::vector<Numerical_Orbital_Lm, std::allocator<Numerical_Orbital_Lm> > > > > > const&, double, double) /root/abacus-develop/source/module_ri/exx_abfs-construct_orbs.cpp:101
    #13 0x56104b0c3028 in Exx_LRI<double>::init(ompi_communicator_t* const&, K_Vectors const&) /root/abacus-develop/source/module_ri/Exx_LRI.hpp:59
    #14 0x56104b137b6f in ModuleESolver::ESolver_KS_LCAO<std::complex<double>, double>::before_all_runners(Input&, UnitCell&) /root/abacus-develop/source/module_esolver/esolver_ks_lcao.cpp:204
    #15 0x56104a99a6e0 in Driver::driver_run() /root/abacus-develop/source/driver_run.cpp:46
    #16 0x56104a9974ee in Driver::atomic_world() /root/abacus-develop/source/driver.cpp:116
    #17 0x56104a999e00 in Driver::init() /root/abacus-develop/source/driver.cpp:37
    #18 0x561049d360c2 in main /root/abacus-develop/source/main.cpp:39

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/c++/11/bits/stl_vector.h:1064 in std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >::operator[](unsigned long) const
Shadow bytes around the buggy address:
  0x0c22801bbf90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22801bbfa0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22801bbfb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22801bbfc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c22801bbfd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c22801bbfe0: fa fa fa fa fa[fa]fa fa 00 00 00 00 00 00 00 00
  0x0c22801bbff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c22801bc000: 00 00 00 00 00 00 fa fa fa fa fa fa fa fa fa fa
  0x0c22801bc010: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c22801bc020: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c22801bc030: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2470==ABORTING
```

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@jinzx10 could you have a look?
