### ISSUE TITLE
Unexpected error occured when running latest ABACUS 3.7.2 with DeePKS-kit

### ISSUE THREAD

**Issue by JohnYan98** [deepmodeling/abacus-develop#4897]
### Describe the bug

When running examples: https://github.com/deepmodeling/deepks-kit/tree/master/examples/water_single, the program stopped abnormally with err.iter:

```
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/__main__.py", line 11, in <module>
    main_cli()
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/main.py", line 37, in main_cli
    sub_cli(args.args)
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/main.py", line 259, in iter_cli
    main(**argdict)
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/iterate/iterate.py", line 349, in main
    iterate.restart()
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/task/workflow.py", line 87, in restart
    self.run((), restart_tag=restart_tag)
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/task/workflow.py", line 42, in run
    self.child_tasks[last_idx].run(last_tag, restart_tag=rest_tag)
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/task/workflow.py", line 42, in run
    self.child_tasks[last_idx].run(last_tag, restart_tag=rest_tag)
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/task/workflow.py", line 49, in run
    task.run(curr_tag)
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/task/task.py", line 88, in run
    self.execute()
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/task/task.py", line 126, in execute
    self.pycallable(*self.call_args, **self.call_kwargs)
  File "/opt/miniconda3/lib/python3.9/site-packages/deepks/iterate/template_abacus.py", line 412, in gather_stats_abacus
    ene = np.load(f"{sys_train_paths[i]}/ABACUS/{f}/e_base.npy")
  File "/opt/miniconda3/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/data/water_single_lda2pbe_abacus/iter/share/systems_train/group.00/ABACUS/0/e_base.npy'
```

### To Reproduce

https://github.com/deepmodeling/deepks-kit/tree/master/examples/water_single

### Environment

registry.dp.tech/dptech/abacus:3.1.4-toolkit-notebook, the ABACUS was updated to the latest version.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by xuan112358** [comment]
@JohnYan98 This happend because ABACUS changed the location of the output .npy files in #4784 , but there was no corresponding change in deepks-kit. I'll change it right away.

**Comment by xuan112358** [comment]
@JohnYan98 Please get the latest code of ABACUS and DeePKS-kit (branch develop) and try again~
