### ISSUE TITLE
The weekly test of interface to DPGEN failed at 20241016

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#5241]
### Describe the Testing Issue

At 20241016, the test of interface to dpgen is failed.

https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-interface-test-ade2fe

The error message is:
```
Traceback (most recent call last):
  File "/opt/mamba/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/main.py", line 255, in main
    args.func(args)
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/data/gen.py", line 1583, in gen_init_bulk
    coll_abacus_md(jdata)
  File "/opt/mamba/lib/python3.10/site-packages/dpgen/data/gen.py", line 1245, in coll_abacus_md
    _sys = dpdata.LabeledSystem(oo, type_map=type_map, fmt="abacus/md")
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 183, in __init__
    self.from_fmt(
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 220, in from_fmt
    return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/system.py", line 1113, in from_fmt_obj
    data = fmtobj.from_labeled_system(file_name, **kwargs)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/plugins/abacus.py", line 66, in from_labeled_system
    return dpdata.abacus.md.get_frame(file_name)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/abacus/md.py", line 175, in get_frame
    coords, cells, force, stress = get_coords_from_dump(dumplines, natoms)
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/abacus/md.py", line 88, in get_coords_from_dump
    np.array([float(i) for i in dumplines[iline + 3 + ix].split()[0:3]])
  File "/opt/mamba/lib/python3.10/site-packages/dpdata/abacus/md.py", line 88, in <listcomp>
    np.array([float(i) for i in dumplines[iline + 3 + ix].split()[0:3]])
ValueError: could not convert string to float: 'LATTICE_CONSTANT:'
```

The error message show that the function of dpdata to get value from MD is destroyed.

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by pxlxingliang** [comment]
I have checked the MD_dump file, and it seems that multiple cores are simultaneously writing content to the file.
@YuLiu98 Could you have a look?

```
MDSTEP:  1
LATTICE_CONSTANT: 1.000000064679 Angstrom
MDSTEP:  1
LATTICE_VECTORS
  5.430900000000  0.000000000000  0.000000000000
MDSTEP:  1
LATTICE_CONSTANT: 1.000000064679 Angstrom
  0.000000000000  5.430900000000  0.000000000000
LATTICE_VECTORS
  0.000000000000  0.000000000000  5.430900000000
LATTICE_CONSTANT: 1.000000064679 Angstrom
  5.430900000000  0.000000000000  0.000000000000
INDEX    LABEL    POSITION (Angstrom)    FORCE (eV/Angstrom)    VELOCITY (Angstrom/fs)
LATTICE_VECTORS
  0.000000000000  5.430900000000  0.000000000000
  5.430900000000  0.000000000000  0.000000000000
  0.000000000000  0.000000000000  5.430900000000
INDEX    LABEL    POSITION (Angstrom)    FORCE (eV/Angstrom)    VELOCITY (Angstrom/fs)
  0.000000000000  5.430900000000  0.000000000000
  0    0.001774710155  5.430428132390  0.001844892851  -0.003193498993  0.068107621947  -0.064358901904  0.001774161597  -0.000460168522  0.001833837694
  0.000000000000  0.000000000000  5.430900000000
INDEX    LABEL    POSITION (Angstrom)    FORCE (eV/Angstrom)    VELOCITY (Angstrom/fs)
  0    0.001774710155  5.430428132390  0.001844892851  -0.003193498993  0.068107621947  -0.064358901904  0.001774161597  -0.000460168522  0.001833837694
  1    0.000507032587  2.713991572092  2.718777304096  -0.042441108561  0.049259650018  -0.046519468708  0.000499742327  -0.001449966403  0.003319313281
  0    0.001774710155  5.430428132390  0.001844892851  -0.003193498993  0.068107621947  -0.064358901904  0.001774161597  -0.000460168522  0.001833837694
  1    0.000507032587  2.713991572092  2.718777304096  -0.042441108561  0.049259650018  -0.046519468708  0.000499742327  -0.001449966403  0.003319313281
  2    2.709608894873  0.001579992773  2.714583133358  0.018897690732  -0.005404054979  -0.049016941386  -0.005837859003  0.001579064499  -0.000875286456
  1    0.000507032587  2.713991572092  2.718777304096  -0.042441108561  0.049259650018  -0.046519468708  0.000499742327  -0.001449966403  0.003319313281
  2    2.709608894873  0.001579992773  2.714583133358  0.018897690732  -0.005404054979  -0.049016941386  -0.005837859003  0.001579064499  -0.000875286456
  3    2.720368280095  2.709796232901  0.000814883006  -0.025358278085  0.117655452301  -0.034285135277  0.004913924214  -0.005633557003  0.000808993727
  2    2.709608894873  0.001579992773  2.714583133358  0.018897690732  -0.005404054979  -0.049016941386  -0.005837859003  0.001579064499  -0.000875286456
```
