### ISSUE TITLE
abacus-plot -b can't recognize the keyword 'efermi' 'energy_r',when I change them, the results still keep unchange.

### ISSUE THREAD

**Issue by gx-dft** [deepmodeling/abacus-develop#5769]
### Describe the bug

Traceback (most recent call last):
  File "/home/xgao/anaconda3/bin/abacus-plot", line 33, in <module>
    sys.exit(load_entry_point('abacus-plot==1.2.0', 'console_scripts', 'abacus-plot')())
  File "/home/xgao/anaconda3/lib/python3.9/site-packages/abacus_plot-1.2.0-py3.9.egg/abacus_plot/main.py", line 134, in main
  File "/home/xgao/anaconda3/lib/python3.9/site-packages/abacus_plot-1.2.0-py3.9.egg/abacus_plot/main.py", line 31, in show_cmdline
  File "/home/xgao/anaconda3/lib/python3.9/site-packages/abacus_plot-1.2.0-py3.9.egg/abacus_plot/band.py", line 250, in plot
  File "/home/xgao/anaconda3/lib/python3.9/site-packages/abacus_plot-1.2.0-py3.9.egg/abacus_plot/band.py", line 289, in _set_figure
IndexError: list index out of range

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by 1041176461** [comment]
Use a single `efermi` value for nspin=1 or 4, a list `[efermi1, efermi2]` for nspin=2, a list `[efermi1, efermi2, efermi3 ...]` for comparing many band structure files
